version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - make install
  build:
    commands:
      - make lint
      - make test
  post_build:
    commands: []

artifacts:
  files: []
