steps:
  # Phase: install
  - name: "python:3.8"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        python --version

  # Phase: pre_build
  - name: "gcr.io/cloud-builders/make"
    args: ["install"]

  # Phase: build
  - name: "gcr.io/cloud-builders/make"
    args: ["lint"]
  - name: "gcr.io/cloud-builders/make"
    args: ["test"]
